version: '2'
services:
  bank1:
    build: .
    command: node app.js 3.3 Evil Corp.
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "rabbitmq"
    networks:
      - rabbitmq_go_net
  
  bank2:
    build: .
    command: node app.js 4.5 Loan Shark
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - "rabbitmq"
    networks:
      - rabbitmq_go_net
  
  bank3:
    build: .
    command: node app.js 8.9 Quick Loan
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      - "rabbitmq"
    networks:
      - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge